### ISSUE TITLE
adminMongo连接不上,文档中服务启停systemctl 修改为docker

### ISSUE THREAD

**Issue by hnczhjh** [Websoft9/ansible-graylog#13]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

![image](https://user-images.githubusercontent.com/86603933/123920196-43d25600-d9b8-11eb-870d-230c3f6ff0a0.png)
![image](https://user-images.githubusercontent.com/86603933/123926468-7aab6a80-d9be-11eb-8b3a-887a98da0d72.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
```
# Add this file 
# Initial login username is admin ,password is admin
# echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1 to create new administrator password
# this docker-compose make from https://docs.graylog.org/en/4.0/pages/installation/docker.html#quick-start

version: '3.8'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:${DB_MONGO_VERSION}
    container_name: ${APP_CONTAINER_NAME}-mongo
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=admin
    ports:
      # mongodb
      - 27017:27017
    volumes: 
      - ${VOLUMES_PATH_PREFIX}/mongodb:/data/db
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: ${APP_CONTAINER_NAME}-elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    restart: always
    volumes: 
      - elasticsearch/:/usr/share/elasticsearch/data
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # echo -n admin | shasum -a 256, default password is admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=${APP_HTTP_EXTERNAL_URI}
      - GRAYLOG_MONGODB_URI=mongodb://root:123456@172.17.0.1:27017/admin
      - GRAYLOG_MONGO_INITDB_ROOT_USERNAME=root
      - GRAYLOG_MONGO_INITDB_ROOT_PASSWORD=123456
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - ${APP_PORT}:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    volumes: 
      - graylog:/usr/share/graylog/data/
      - ${VOLUMES_PATH_PREFIX}/plugin:/usr/share/graylog/plugin

volumes: 
  graylog:
  elasticsearch:
  
networks:
  default:
      name: ${APP_NETWORK}
```
